services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather_user -d weather_dashboard"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
