services:
  - type: web
    name: weather-dashboard-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn 'wsgi:app'  # Note the quotes and correct path
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: WEATHER_API_KEY
        sync: false